VERSION = ${mod_version}
MOD_ID = ${mod_id}
MOD_NAME = ${mod_name}
DEPENDENCIES = required-after:night_config@[1.0.1,);
CLIENT_PROXY_PATH = ${root_package}.${mod_id}.proxy.ClientProxy
SERVER_PROXY_PATH = ${root_package}.${mod_id}.proxy.CommonProxy